### ISSUE TITLE
New dataset request SCAN

### ISSUE THREAD

**Issue by kevinlove** [bio-guoda/guoda-datasets#11]
The SCAN dataset is currently at 14,555,375 occurrence records and these data are hosted on iDigBio infrastructure.

**Comment by godfoder** [comment]
Is there anything in the SCAN dataset that isn't in iDigBio/GBIF already? If so, could those pieces be identified independently?

If there is enough neccessity to have SCAN have its own artifacts, I'd prefer to have something like this be generated as a subset of our existing parquets, rather than a novel ingestion. The Filter -> Reshape -> Union -> Persist workflow is way more straightforward that the DwC-A ingest workflow, so minimizing ingests to just novel data reduces overall system complexity.

**Comment by jhpoelen** [comment]
Closing stale issue.
